[workspace]
members = [
    "space-engine",
    "triangle-example",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Firestar99"]
edition = "2021"
license = "MIT"
repository = "https://gitlab.com/spacegamedev/space-rust"

[workspace.dependencies]
# vulkan
# vulkano 0.33 with this PR included https://github.com/vulkano-rs/vulkano/pull/2180
vulkano = { git = "https://github.com/vulkano-rs/vulkano", rev = "62ff8b45a51489b64db4679148b169df18bc565f" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano", rev = "62ff8b45a51489b64db4679148b169df18bc565f" }
vulkano-win = { git = "https://github.com/vulkano-rs/vulkano", rev = "62ff8b45a51489b64db4679148b169df18bc565f" }
bytemuck = { version = "1.7" } # in sync with vulkano-win
winit = "0.28" # in sync with vulkano-win

# rust-gpu
spirv-builder = { version = "0.9", default-features = false }
spirv-std = { version = "0.9" }

# async
futures = "0.3"
async-global-executor = { version = "2.3.1" }
async-std = { version = "1.12", features = ["attributes"] }

# other
parking_lot = "0.12"
clap = { version = "3.2", features = ["derive"] }
konst = "0.3.4"
paste = "1.0.9"
num-traits = "0.2"
num-derive = "0.3"

# Following is copied from rust-gpu workspace cargo.toml
# Enable incremental by default in release mode.
[profile.release]
incremental = true
# HACK(eddyb) this is the default but without explicitly specifying it, Cargo
# will treat the identical settings in `[profile.release.build-override]` below
# as different sets of `rustc` flags and will not reuse artifacts between them.
codegen-units = 256

# Compile build-dependencies in release mode with the same settings
# as regular dependencies (including the incremental enabled above).
[profile.release.build-override]
opt-level = 3
incremental = true
codegen-units = 256
