[workspace]
members = [
    "asteroids",
    "asteroids-shader",
    "asteroids-common",
    "shader-symbols-builder",
    "space-engine",
    "space-engine-common",
    "space-engine-shader",
    "space-engine-shader-builder",
    "vulkano-bindless/vulkano-bindless",
    "vulkano-bindless/vulkano-bindless-shaders",
]
resolver = "2"



[workspace.package]
version = "0.1.0"
authors = ["Firestar99"]
edition = "2021"
license = "MIT"
repository = "https://gitlab.com/spacegamedev/space-rust"



[workspace.dependencies]
# vulkan
# vulkano 0.35 development, PR https://github.com/vulkano-rs/vulkano/pull/2482
vulkano = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "4c2d7c584adcde6a8e3f4b9c3f24fd2f1b1e28bc" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "4c2d7c584adcde6a8e3f4b9c3f24fd2f1b1e28bc" }
winit = { version = "0.29.9", features = ["rwh_05"] }

# rust-gpu
spirv-builder = { git = "https://github.com/Firestar99/rust-gpu", rev = "05e8c8df6c5577c23afdc43ad90df591a92fdca0", default-features = false }
spirv-std = { git = "https://github.com/Firestar99/rust-gpu", rev = "05e8c8df6c5577c23afdc43ad90df591a92fdca0", version = "0.9" }

# async
futures = "0.3"
smol = "1.3.0"

# codegen
quote = "1.0"
proc-macro2 = "1.0"
syn = "2.0"
paste = "1.0"
konst = "0.3"
prettyplease = "0.2"

# bytes and numbers
glam = { version = "0.24", default-features = false, features = ["libm", "bytemuck"] }
bytemuck = "1.13"
bytemuck_derive = "1.4"
num-traits = { version = "0.2", default-features = false, features = ["libm"] }
num-derive = "0.3"

# model loader
gltf = "1.4.0"
image = { version = "0.24.7", default-features = false, features = ["jpeg", "png"] }

# other
once_cell = "1.18"
smallvec = { version = "1.11", features = ["const_generics", "const_new"] }
static_assertions = "1.1.0"
parking_lot = "0.12"
clap = { version = "3.2", features = ["derive"] }



# Following is copied from rust-gpu workspace cargo.toml
# Enable incremental by default in release mode.
[profile.release]
incremental = true
# HACK(eddyb) this is the default but without explicitly specifying it, Cargo
# will treat the identical settings in `[profile.release.build-override]` below
# as different sets of `rustc` flags and will not reuse artifacts between them.
codegen-units = 256

# Compile build-dependencies in release mode with the same settings
# as regular dependencies (including the incremental enabled above).
[profile.release.build-override]
opt-level = 3
incremental = true
codegen-units = 256



# Optimize certain crates even in dev mode:
# model and image loading
[profile.dev.package.gltf]
opt-level = 3
[profile.dev.package.gltf-derive]
opt-level = 3
[profile.dev.package.gltf-json]
opt-level = 3
[profile.dev.package.image]
opt-level = 3
[profile.dev.package.png]
opt-level = 3
[profile.dev.package.jpeg-decoder]
opt-level = 3
