pub mod bindless;
pub mod bindless_descriptor_allocator;
pub mod buffer_metadata_cpu;
pub mod buffer_table;
pub mod descriptor_content;
pub mod descriptor_counts;
pub mod image_table;
pub mod rc_reference;
pub mod resource_table;
pub mod sampler_table;

pub use bindless::{Bindless, BindlessLock, PushConstantError, BINDLESS_MAX_PUSH_CONSTANT_WORDS};
pub use buffer_table::{BufferTable, BufferTableAccess, StrongBackingRefs};
pub use descriptor_content::{DescContent, DescContentCpu, DescContentEnum, DescTable};
pub use descriptor_counts::DescriptorCounts;
pub use image_table::{ImageTable, ImageTableAccess};
pub use rc_reference::{AnyRCDesc, AnyRCDescExt, RCDesc, RCDescExt, RC};
pub use resource_table::ResourceTable;
pub use sampler_table::{SamplerTable, SamplerTableAccess};
pub use vulkano_bindless_shaders::descriptor::*;
