[package]
name = "asteroids"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["use-installed-tools"]
use-installed-tools = ["shader-symbols-builder/use-installed-tools"]
use-compiled-tools = ["shader-symbols-builder/use-compiled-tools"]

[dependencies]
# my projects
asteroids-common = { path = "../asteroids-common" }
space-engine = { path = "../space-engine" }
space-engine-common = { path = "../space-engine-common" }

# vulkan
vulkano = { workspace = true }
vulkano-shaders = { workspace = true }
winit = { workspace = true }

# async
futures = { workspace = true }
smol = { workspace = true }

# bytes and numbers
glam = { workspace = true }
bytemuck = { workspace = true }
bytemuck_derive = { workspace = true }
num-traits = { workspace = true }
num-derive = { workspace = true }

# other
static_assertions = { workspace = true }
parking_lot = { workspace = true }
smallvec = { workspace = true }

[build-dependencies]
shader-symbols-builder = { path = "../shader-symbols-builder", features = ["use-pretty-print"] }
