[package]
name = "vulkano-bindless-shaders-rust"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
spirv-std = "0.9.0"
