[package]
name = "space-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
default-run = "start"

[dependencies]
space-engine = { path = "../space-engine" }
vulkano = { workspace = true }
vulkano-win = { workspace = true }
clap = { workspace = true }
parking_lot = { workspace = true }
