[package]
name = "shader-symbols"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vulkano = { workspace = true }
