[package]
name = "space-engine-shader-builder"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vulkano-bindless-shader-builder = { workspace = true }
