[package]
name = "space-engine"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vulkano = { workspace = true }
vulkano-win = { workspace = true }
konst = { workspace = true }
parking_lot = { workspace = true }
paste = { workspace = true }
