[package]
name = "space-engine"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# vulkan
vulkano = { workspace = true }
vulkano-win = { workspace = true }
winit = { workspace = true }

# async
futures = { workspace = true }
async-std = { workspace = true }
async-global-executor = { workspace = true }

# other
konst = { workspace = true }
parking_lot = { workspace = true }
paste = { workspace = true }
num-traits = { workspace = true }
num-derive = { workspace = true }
